language: node_js
node_js:
  - "8.2.1"

install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version

script:
  - npm run test-ci

after_success:
  - node scripts/triggerDocSiteBuild.js
